name: DEPLOY TO PROD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        
      - name: installing dependencies...
        run: npm install

      - name: building project...
        run: npm run build
        
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          VUE_APP_OpenWeatherKey: ${{ secrets.VUE_APP_OpenWeatherKey }}
          VUE_APP_GOOGLE_KEY: ${{ secrets.VUE_APP_GOOGLE_KEY }}
          VUE_APP_FIREBASE_KEY: ${{ secrets.VUE_APP_FIREBASE_KEY }}
          VUE_APP_FIREBASE_AUTHDOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTHDOMAIN }}
          VUE_APP_FIREBASE_DATABASE_URL: ${{ secrets.VUE_APP_FIREBASE_DATABASE_URL }}
          VUE_APP_FIREBASE_PROJECTID: ${{ secrets.VUE_APP_FIREBASE_PROJECTID }}
          VUE_APP_FIREBASE_STORAGEBUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGEBUCKET }}
          VUE_APP_FIREBASE_MESSAGEINGSENDERID: ${{ secrets.VUE_APP_FIREBASE_MESSAGEINGSENDERID }}
          VUE_APP_FIREBASE_APPID: ${{ secrets.VUE_APP_FIREBASE_APPID }}
          VUE_APP_FIREBASE_MEASUREMENTID: ${{ secrets.VUE_APP_FIREBASE_MEASUREMENTID }}
